apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n8wlru5y6-nodejs
  janus-idp.io/tekton: n8wlru5y6-nodejs
  backstage.io/kubernetes-id: n8wlru5y6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n8wlru5y6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
